#!/usr/bin/env bats
# Tests for action.sh.
#
# Fixtures use an obviously-fake version (v9.9.9, not a real vcluster-pro
# release line) and fake images/repos (example-org/...), never real
# ghcr.io/loft-sh/* names or plausible real version numbers, so nobody
# mistakes test data for a real artifact.

bats_require_minimum_version 1.5.0

SCRIPT="$BATS_TEST_DIRNAME/../src/action.sh"

load gh_mock
load crane_mock

# Sets GH_MOCK_RELEASE_LIST_<repo> so the ordering predicates see a release
# history for that repo (see gh_mock.bash for the varname sanitization).
set_release_list() {
  local repo="$1" json="$2"
  local varname
  varname="GH_MOCK_RELEASE_LIST_$(printf '%s' "$repo" | tr -c 'A-Za-z0-9' '_')"
  export "$varname=$json"
}

# Points the `gh api GET repos/.../contents/<path>` mock at a real fixture
# file for the given full API path (e.g. "repos/example-org/example-tap/
# contents/Formula/vcluster.rb").
set_contents_fixture() {
  local api_path="$1" file="$2" sha="${3:-fakesha}"
  local suffix
  suffix="$(printf '%s' "$api_path" | tr -c 'A-Za-z0-9' '_')"
  export "GH_MOCK_CONTENTS_FILE_${suffix}=${file}"
  export "GH_MOCK_CONTENTS_SHA_${suffix}=${sha}"
}

# Points the `gh release download` mock at a real checksums.txt fixture for
# the given repo.
set_checksums_fixture() {
  local repo="$1" file="$2"
  local varname
  varname="GH_MOCK_CHECKSUMS_$(printf '%s' "$repo" | tr -c 'A-Za-z0-9' '_')"
  export "$varname=$file"
}

# Path the mock writes a PUT's decoded content to, for the given API path.
put_output_path() {
  printf '%s/put_%s.out' "$GH_MOCK_DIR" "$(printf '%s' "$1" | tr -c 'A-Za-z0-9' '_')"
}

write_fake_formula() {
  cat > "$1" <<'RUBY'
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  desc "Example fake formula for tests"
  homepage "https://example.com"
  version "9.0.0"
  license "Apache-2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-darwin-amd64"
      sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"

      define_method(:install) do
        bin.install "vcluster-darwin-amd64" => "vcluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-linux-amd64"
      sha256 "bbbb000000000000000000000000000000000000000000000000000000bbbb"
      define_method(:install) do
        bin.install "vcluster-linux-amd64" => "vcluster"
      end
    end
  end

  conflicts_with "vcluster-experimental"

  test do
    help_output = "vcluster root command"
    assert_match help_output, shell_output("#{bin}/vcluster --help")
  end
end
RUBY
}

write_fake_checksums() {
  cat > "$1" <<'CHECKSUMS'
cccc111111111111111111111111111111111111111111111111111111cccc  vcluster-darwin-amd64
dddd222222222222222222222222222222222222222222222222222222dddd  vcluster-linux-amd64
CHECKSUMS
}

# A formula that carries a top-level `version` AND a nested resource stanza
# with its own `version` pin, to prove only the top-level one is rewritten.
write_fake_formula_with_resource() {
  cat > "$1" <<'RUBY'
# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  desc "Example fake formula for tests"
  version "9.0.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-darwin-amd64"
    sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"
  end

  resource "vendored-lib" do
    url "https://example.com/vendored-lib/1.2.3.tar.gz"
    version "1.2.3"
    sha256 "eeee000000000000000000000000000000000000000000000000000000eeee"
  end

  test do
    assert_match "vcluster", shell_output("#{bin}/vcluster --help")
  end
end
RUBY
}

# A formula whose two artifacts differ only where a regex `.` metacharacter
# would blur them (`vcluster-plugin.amd64` vs `vcluster-pluginxamd64`). A
# literal matcher keeps each url bound to its own sha256; a regex one would
# cross-contaminate them.
write_fake_formula_metachar() {
  cat > "$1" <<'RUBY'
# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  version "9.0.0"

  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-plugin.amd64"
    sha256 "1111000000000000000000000000000000000000000000000000000000aaaa"
  end

  on_linux do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-pluginxamd64"
    sha256 "2222000000000000000000000000000000000000000000000000000000bbbb"
  end
end
RUBY
}

write_fake_checksums_metachar() {
  cat > "$1" <<'CHECKSUMS'
aaaa333333333333333333333333333333333333333333333333333333aaaa  vcluster-plugin.amd64
bbbb444444444444444444444444444444444444444444444444444444bbbb  vcluster-pluginxamd64
CHECKSUMS
}

setup() {
  setup_gh_mock
  setup_crane_mock
  export GH_TOKEN="fake-token"
  export GITHUB_REPOSITORY="example-org/example-caller-repo"
  export INPUT_VERSION="v9.9.9"
  export INPUT_IMAGES='[{"image":"ghcr.io/example-org/example-image"},{"image":"ghcr.io/example-org/example-image","suffix":"-fips"}]'
  export INPUT_OSS_REPO="example-org/example-repo"
  export INPUT_DRY_RUN="false"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9"

  FIXTURES_DIR="$(mktemp -d)"
  write_fake_formula "$FIXTURES_DIR/vcluster.rb"
  write_fake_checksums "$FIXTURES_DIR/checksums.txt"
}

teardown() {
  teardown_gh_mock
  teardown_crane_mock
  rm -rf "$FIXTURES_DIR"
}

@test "happy path -> retags latest/major/minor for every image entry, including suffix" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:latest-fips ghcr.io/example-org/example-image:9.9.9-fips' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9-fips ghcr.io/example-org/example-image:9.9.9-fips' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-fips ghcr.io/example-org/example-image:9.9.9-fips' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "per-arch suffix entries -> retag per-arch moving tags from the per-arch version source" {
  # DEVOPS-1083: the per-arch moving tags (latest-amd64, latest-fips-arm64v8,
  # ...) are promoted purely as suffix entries -- each copies the bare
  # single-platform source <image>:X.Y.Z<suffix> onto its moving tags.
  # crane makes this digest-preserving (imagetools would not); here we assert
  # the retag targets are wired correctly for the per-arch suffixes.
  export INPUT_IMAGES='[{"image":"ghcr.io/example-org/example-image","suffix":"-amd64"},{"image":"ghcr.io/example-org/example-image","suffix":"-fips-arm64v8"}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest-amd64 ghcr.io/example-org/example-image:9.9.9-amd64' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9-amd64 ghcr.io/example-org/example-image:9.9.9-amd64' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-amd64 ghcr.io/example-org/example-image:9.9.9-amd64' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:latest-fips-arm64v8 ghcr.io/example-org/example-image:9.9.9-fips-arm64v8' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9-fips-arm64v8 ghcr.io/example-org/example-image:9.9.9-fips-arm64v8' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-fips-arm64v8 ghcr.io/example-org/example-image:9.9.9-fips-arm64v8' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "happy path -> promotes the paired oss-repo release" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "newest stable over a non-empty prior-stable history -> advances :latest/:major" {
  # The happy path above drives the ordering predicates with an empty list,
  # so it only exercises the `[ -z "${max}" ]` short-circuit. This is the real
  # forward-promotion case: a prior promoted release exists and VERSION is
  # newer, so the `sort -V | tail -1` comparison must resolve true and :latest
  # still advances.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "newer un-promoted stable cut -> does NOT block :latest (None-label baseline)" {
  # The reason the unscoped baseline is the isLatest pointer and not "newest
  # isPrerelease == false": under release.prerelease: auto, v10.0.0 can exist
  # as a published-but-un-promoted stable cut (the GitHub "None" label - not a
  # pre-release, not Latest). It is NOT what :latest tracks, so promoting
  # v9.9.9 must still advance :latest. Reading the old flag here would strand
  # :latest until someone promoted v10.0.0.
  #
  # v9.9.8 carries the Latest flag, so this isolates the one variable under
  # test: an un-promoted NEWER cut in the list. The old isPrerelease-based
  # baseline would have picked v10.0.0 here and refused. (The separate case of
  # no Latest flag at ALL is a different state - see the fallback test below -
  # because a cleared flag is indistinguishable from a never-promoted repo and
  # must not be read as "anything may advance".)
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isPrerelease":false,"isLatest":true},{"tagName":"v10.0.0","isPrerelease":false,"isLatest":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "a prerelease-shaped tag flagged Latest remains the overall baseline" {
  # GitHub permits a human to flag any release Latest. The overall gate must
  # respect that pointer even when its immutable tag is not stable-shaped.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.9-rc.1","isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Latest-flagged release v9.9.9-rc.1"* ]]
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':9 ' "$CRANE_MOCK_CALLS"
  grep -qF ':9.9 ' "$CRANE_MOCK_CALLS"
}

@test "multiple Latest flags conservatively use the newest flagged tag" {
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isLatest":true},{"tagName":"v10.0.0","isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Latest-flagged release v10.0.0"* ]]
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
}

@test "re-promoting the release already flagged Latest -> still advances (idempotent re-run)" {
  # A promotion that got part-way (docker retags failed, tap left stale) has to
  # be re-runnable. VERSION == the current Latest must therefore resolve as
  # promotable rather than reading as "older than the promoted release".
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.9","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "releases exist but none is flagged Latest -> falls back to the newest stable tag, no backward :latest" {
  # The Latest flag is CLEARABLE: goreleaser re-asserts make_latest: false on
  # every run, so re-running the build for the tag that currently holds it
  # leaves the repo with releases but no isLatest. An empty isLatest must
  # therefore NOT read as "first-ever promotion" - doing so would let this
  # dispatch for the older v9.9.9 drag :latest/:9 back off v10.0.0.
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.9","isPrerelease":false,"isLatest":false},{"tagName":"v10.0.0","isPrerelease":false,"isLatest":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no release on example-org/example-caller-repo carries the Latest flag"* ]]
  [[ "$output" == *"newest stable tag (v10.0.0)"* ]]

  # :latest/:9 must stay put; the line tag is still allowed to advance.
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  # ... and the caller's own release must not be flipped to Latest either.
  grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "no releases at all -> genuine first-ever promotion still advances" {
  # The fallback above must not turn an actually-empty repo into a permanent
  # refusal: with no releases there is nothing to regress, so :latest advances.
  set_release_list "$GITHUB_REPOSITORY" '[]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  run ! grep -q 'carries the Latest flag' <<<"$output"

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "line gate ignores the mutable prerelease flag on a stable-shaped sibling" {
  # :9.9 already points at v9.9.10. Re-running that release's build under the
  # legacy release.prerelease: true config re-flags it isPrerelease. If the
  # line gate filtered on that flag, v9.9.10 would drop out of the comparison,
  # v9.9.9 would look newest in its line, and :9.9 would be retagged BACKWARDS.
  # The gate keys on tag shape only, so the regression can't happen.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.10","isPrerelease":true,"isLatest":false},{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"is not the newest stable release in the 9.9 line"* ]]

  run ! grep -qF ':9.9 ' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "non-stable version (has a suffix) -> no-op, no docker or gh calls" {
  export INPUT_VERSION="v9.9.9-rc.1"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [ ! -s "$CRANE_MOCK_CALLS" ]
  [ ! -s "$GH_MOCK_CALLS" ]
}

@test "every unstable suffix shape is a no-op -> never touches :latest or --latest" {
  # A dispatch can name ANY tag, so this action can be handed an
  # rc/alpha/beta/next cut too - this is the guard that stops that from ever
  # moving :latest.
  for version in \
    "v9.9.9-rc.1" \
    "v9.9.9-alpha.1" \
    "v9.9.9-beta.2" \
    "v9.9.9-next.3" \
    "v9.9.9-next.internal.7"
  do
    export INPUT_VERSION="$version"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" == *"is not a stable vX.Y.Z release"* ]]
    [ ! -s "$CRANE_MOCK_CALLS" ]
    [ ! -s "$GH_MOCK_CALLS" ]
  done
}

@test "oss-repo has no matching release -> warns, still retags docker, does not edit" {
  export GH_MOCK_KNOWN_RELEASES=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no v9.9.9 release found on example-org/example-repo"* ]]
  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "empty oss-repo -> skips the paired release entirely" {
  export INPUT_OSS_REPO=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  # A "LIST" call for GITHUB_REPOSITORY's own backport check is expected;
  # what must NOT happen is any view/edit call touching an oss-repo.
  run ! grep -q '^VIEW \|^EDIT ' "$GH_MOCK_CALLS"
}

@test "promote-self off by default -> caller's own release is never touched" {
  # Default must stay off: a caller that publishes stable cuts as real releases
  # (prerelease: true, promoted by hand) would otherwise have its release
  # flipped unasked.
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"promote-self not enabled"* ]]
  run ! grep -qF 'EDIT example-org/example-caller-repo' "$GH_MOCK_CALLS"
}

@test "promote-self -> unsets prerelease and sets latest on the caller's own release" {
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
  # The paired oss-repo release is still promoted independently.
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "promote-self on a backport -> unsets prerelease but does not move Latest" {
  # Same gate as :latest/:major, so promoting an older line never moves the
  # repo's Latest pointer backwards.
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not marking example-org/example-caller-repo@v9.9.9 as Latest"* ]]
  grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "promote-self: a failed Latest edit is fatal and happens before any retag" {
  # The caller's Latest pointer is this action's own backport baseline, so it
  # is established BEFORE the moving tags advance. If it cannot be set, nothing
  # may be retagged: :latest ahead of a stale baseline is exactly what lets a
  # later older-line promotion drag :latest backwards.
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  export GH_MOCK_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 1 ]
  [[ "$output" == *"failed to set example-org/example-caller-repo@v9.9.9 as Latest"* ]]
  # Nothing at all should have moved: no retags, no oss-repo promotion.
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
  run ! grep -qF -- 'EDIT example-org/example-repo' "$GH_MOCK_CALLS"
}

@test "promote-self: an unreadable caller release on an advancing promotion is fatal" {
  # `gh release view` exits non-zero both for "no such release" and for a
  # transient API error; the two are indistinguishable. An advancing promotion
  # must establish the pointer, so neither may be skipped with a warning - that
  # would retag :latest and leave the baseline behind it.
  export INPUT_PROMOTE_SELF="true"
  run "$SCRIPT"
  [ "$status" -eq 1 ]
  [[ "$output" == *"no v9.9.9 release found on example-org/example-caller-repo"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
  run ! grep -qF 'EDIT ' "$GH_MOCK_CALLS"
}

@test "promote-self: an API lookup failure is reported accurately and fails before retagging" {
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_VIEW_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 1 ]
  [[ "$output" == *"failed to inspect example-org/example-caller-repo@v9.9.9"* ]]
  [[ "$output" == *"forced release view API failure"* ]]
  [[ "$output" != *"no v9.9.9 release found"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "promote-self: a failed edit on a BACKPORT stays a warning (no pointer moved)" {
  # Here the edit is --prerelease=false only: it moves no pointer, so it cannot
  # stale a baseline and must not take the run down with it.
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  export GH_MOCK_FAIL=1
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"gh release edit failed for example-org/example-caller-repo@v9.9.9"* ]]
}

@test "promote-self with no matching release on the caller repo, BACKPORT -> warns, run still succeeds" {
  # On a backport nothing advances, so there is no Latest pointer to establish
  # and a missing release cannot stale a baseline. The line tag must still be
  # allowed to advance, so this stays a warning rather than the fatal path.
  export INPUT_PROMOTE_SELF="true"
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no v9.9.9 release found on example-org/example-caller-repo"* ]]
  run ! grep -qF 'EDIT example-org/example-caller-repo' "$GH_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
}

@test "promote-self lookup failure on a backport preserves the real error" {
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_VIEW_FAIL=1
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to inspect example-org/example-caller-repo@v9.9.9"* ]]
  [[ "$output" == *"forced release view API failure"* ]]
  [[ "$output" != *"no v9.9.9 release found on example-org/example-caller-repo"* ]]
}

@test "promote-self -> only an exact 'true' enables it" {
  export INPUT_PROMOTE_SELF="True"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  run ! grep -qF 'EDIT example-org/example-caller-repo' "$GH_MOCK_CALLS"
}

@test "promote-self under dry-run with no release yet -> rehearsal still completes" {
  # A rehearsal may legitimately run before the release exists; the source
  # manifest pre-flight warns instead of aborting under dry-run for the same
  # reason. The fatal unreadable-release branch must not fire here, or a pre-publication
  # preview of an advancing promotion would be impossible.
  export INPUT_PROMOTE_SELF="true"
  export INPUT_DRY_RUN="true"
  export GH_MOCK_KNOWN_RELEASES=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"dry-run: printing the planned promotion anyway"* ]]
  # The planned edit and the planned retags are both still shown...
  [[ "$output" == *"[dry-run] gh release edit v9.9.9 --repo example-org/example-caller-repo --prerelease=false --latest"* ]]
  [[ "$output" == *"[dry-run] crane tag"* ]]
  # ...and nothing was actually mutated.
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "promote-self under dry-run -> reads the release but makes no edit" {
  export INPUT_PROMOTE_SELF="true"
  export INPUT_DRY_RUN="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'VIEW example-org/example-caller-repo v9.9.9' "$GH_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
}

@test "dry-run -> prints planned retags, makes no real docker calls" {
  export INPUT_DRY_RUN="true"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"[dry-run] crane tag ghcr.io/example-org/example-image:9.9.9 latest"* ]]
  [[ "$output" == *"[dry-run] crane tag ghcr.io/example-org/example-image:9.9.9-fips latest-fips"* ]]
  # A rehearsal may read the registry - the existence lookup is what proves the
  # printed plan could actually run - but must not write to it.
  run ! grep -q '^CREATE ' "$CRANE_MOCK_CALLS"
}

@test "fail-closed dry-run -> any value that isn't exactly 'false' makes no real mutations" {
  # The safety inversion this guards: a caller who passes an ambiguous value
  # meaning to PREVIEW must never trigger a real GHCR retag / release flip.
  # Only an exact (case-insensitive) "false" promotes for real.
  for value in "true" "True" "TRUE" "yes" "1" "flase" "false " " false"; do
    : > "$CRANE_MOCK_CALLS"
    : > "$GH_MOCK_CALLS"
    export INPUT_DRY_RUN="$value"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
    run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
  done
}

@test "fail-closed dry-run -> an unrecognized value warns and stays dry" {
  export INPUT_DRY_RUN="ture"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"unrecognized dry-run value 'ture'"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "fail-closed dry-run -> exact 'false' (and case variants) promotes for real" {
  # The default is 'false', so a plain dispatch still promotes; the
  # case-insensitive match means FALSE/False also cut for real rather than
  # silently degrading to a no-op.
  for value in "false" "False" "FALSE"; do
    : > "$CRANE_MOCK_CALLS"
    export INPUT_DRY_RUN="$value"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
  done
}

@test "dry-run -> still reads oss-repo state but does not edit it" {
  export INPUT_DRY_RUN="true"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
}

@test "backport on caller repo -> skips :latest/:major, still advances :major.minor" {
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"older than the promotion baseline on example-org/example-caller-repo"* ]]
  [[ "$output" == *"behind the caller's promotion baseline"* ]]

  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-fips ghcr.io/example-org/example-image:9.9.9-fips' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':9 ' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 2 ]

  # The paired repo may have a stale Latest pointer after an earlier advisory
  # edit failure. The caller is the Docker-tag baseline and therefore the
  # authoritative upper bound: a caller backport must never move OSS Latest.
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "backport across minor lines (same major) -> still skips :latest/:major" {
  # Same shape as: promoting v0.35.6 after v0.36.0 already exists - a
  # same-major, older-minor patch. Distinct from the other backport test,
  # which only exercises a major-version jump (v9.9.9 vs v10.0.0); sort -V's
  # minor-component comparison is a separate thing to get right.
  export INPUT_VERSION="v9.35.6"
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.36.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"older than the promotion baseline on example-org/example-caller-repo"* ]]

  grep -qF 'CREATE ghcr.io/example-org/example-image:9.35 ghcr.io/example-org/example-image:9.35.6' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':9 ' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 2 ]
}

@test "same-minor out-of-order promotion -> skips :major.minor so the line tag can't regress" {
  # :9.9 already points at the newer v9.9.10 in the same line; someone then
  # dispatches a promotion for the older v9.9.9.
  # It's not newest overall, so :latest/:9 are skipped - and because it's not
  # newest within its OWN 9.9 line either, :9.9 must be skipped too. Advancing
  # :9.9 here would silently regress it from v9.9.10 back to v9.9.9.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.10","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"is not the newest stable release in the 9.9 line"* ]]
  [[ "$output" == *"no moving tags to advance"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "newest within its own line but not overall -> advances only :major.minor" {
  # v9.9.9 is the newest patch in the 9.9 line, but v10.0.0 exists overall.
  # This is the ordinary backport: :latest/:9 stay put, :9.9 still advances
  # (it isn't regressing - v9.9.9 IS the newest in its line).
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isPrerelease":false},{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':latest ' "$CRANE_MOCK_CALLS"
  run ! grep -qF ':9 ' "$CRANE_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 2 ]
}

@test "backport on oss-repo -> paired release unsets prerelease but omits --latest" {
  set_release_list "$INPUT_OSS_REPO" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"older than the promotion baseline on example-org/example-repo"* ]]

  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"

  # The caller repo's own history is unaffected: docker tags fully advance.
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "oss-repo list failure (post-retag) -> soft-skips --latest, does not hard-fail the run" {
  # The caller-repo list runs pre-retag and still succeeds, so docker fully
  # retags. Only the oss-repo list fails - and it's post-retag, gating only the
  # advisory --latest. It must warn-skip --latest (never move it backward),
  # still unset prerelease, and keep the run green rather than hard-failing
  # after the irreversible retags already completed.
  export GH_MOCK_LIST_FAIL_REPO="$INPUT_OSS_REPO"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"skipping the advisory --latest promotion"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "caller-repo list failure (pre-retag) -> still fails closed with no retags" {
  # Contrast to the oss-repo case above: the caller-repo gate is pre-retag, so
  # an inability to determine ordering must hard-fail loudly (a green no-op
  # would hide a promotion that silently moved nothing).
  export GH_MOCK_LIST_FAIL_REPO="$GITHUB_REPOSITORY"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"failed to list releases on example-org/example-caller-repo"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "gh release list failure -> fails closed, does not treat it as no prior releases" {
  export GH_MOCK_LIST_FAIL=1
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"failed to list releases on example-org/example-caller-repo"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "malformed release list response -> fails closed before any retag" {
  set_release_list "$GITHUB_REPOSITORY" 'not-json'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"unexpected release-list response"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "parseable release list with an invalid tagName type -> fails closed" {
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":123,"isLatest":false}]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"unexpected release-list response"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "missing source manifest for a suffix variant -> fails before any create call" {
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"source manifest ghcr.io/example-org/example-image:9.9.9-fips does not exist"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "docker refs use the bare version tag, never the v-prefixed release tag" {
  # goreleaser publishes image tags from `{{ .Version }}`, which strips the
  # leading v, so a promotion that composes its source ref from the release tag
  # looks up a manifest that was never pushed and aborts on every entry. Assert
  # the tag namespace directly: no crane call may ever name :v9.9.9, and the
  # release edits must still use the v-prefixed tag.
  export INPUT_PROMOTE_SELF="true"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9 example-org/example-caller-repo:v9.9.9"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  # `run !`, not a bare `!`: errexit does not apply to a negated command, so a
  # bare `!` on a non-final line is inert and would keep this test green on a
  # regression - and this is the assertion carrying the whole invariant.
  run ! grep -q ':v9\.9\.9' "$CRANE_MOCK_CALLS"
  grep -qF 'INSPECT ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
  # The release side keeps the git tag form.
  grep -qF -- 'EDIT example-org/example-caller-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "dry-run with a missing source manifest -> warns per entry, summarizes, still rehearses" {
  # The rehearsal exists to answer "would this promotion work". Skipping the
  # existence lookup under dry-run made it answer yes for a plan that could not
  # execute, so the lookup runs either way and only the verdict differs.
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9 ghcr.io/example-org/example-image:9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"source manifest ghcr.io/example-org/example-image:9.9.9 does not exist; a real promotion would abort"* ]]
  [[ "$output" == *"2 of 2 source manifests could not be resolved at :9.9.9"* ]]
  # Still a rehearsal: the plan is printed and nothing is retagged for real.
  [[ "$output" == *"[dry-run] crane tag ghcr.io/example-org/example-image:9.9.9 latest"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "dry-run with sources present -> no missing-manifest warning" {
  export INPUT_DRY_RUN="true"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" != *"does not exist"* ]]
  [[ "$output" != *"could not be inspected"* ]]
  # Reject the string the aggregate actually emits, so a counter that increments
  # on a successful lookup can't leave this test green.
  [[ "$output" != *"source manifests could not be resolved"* ]]
  grep -qF 'INSPECT ghcr.io/example-org/example-image:9.9.9' "$CRANE_MOCK_CALLS"
}

@test "real run with several unresolved sources -> reports every one, then aborts" {
  # A tag-form mistake breaks every entry at once. Aborting on the first would
  # make that one re-dispatch per image to discover, and the loop is read-only,
  # so there is nothing to protect by stopping early.
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9 ghcr.io/example-org/example-image:9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"source manifest ghcr.io/example-org/example-image:9.9.9 does not exist"* ]]
  [[ "$output" == *"source manifest ghcr.io/example-org/example-image:9.9.9-fips does not exist"* ]]
  [[ "$output" == *"2 of 2 source manifests could not be resolved"* ]]
  # The fatal path carries the tag-form diagnosis too, not just the rehearsal.
  [[ "$output" == *"their tags read 9.9.9 rather than v9.9.9"* ]]
  [[ "$output" == *"Refusing to start retagging"* ]]
  # Still fail-closed: nothing was retagged and the release was never edited.
  run ! grep -q '^CREATE ' "$CRANE_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
}

@test "unresolved sources -> verdict is written to the step summary, not only annotations" {
  # A rehearsal stays green, and ~45 per-entry warnings are easy to mistake for
  # a clean pass once an annotations panel collapses them.
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9"
  GITHUB_STEP_SUMMARY="$BATS_TEST_TMPDIR/summary.md"
  export GITHUB_STEP_SUMMARY
  : > "$GITHUB_STEP_SUMMARY"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF '1/2 sources unresolved at :9.9.9' "$GITHUB_STEP_SUMMARY"
}

@test "all sources resolved -> nothing is written to the step summary" {
  GITHUB_STEP_SUMMARY="$BATS_TEST_TMPDIR/summary.md"
  export GITHUB_STEP_SUMMARY
  : > "$GITHUB_STEP_SUMMARY"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [ ! -s "$GITHUB_STEP_SUMMARY" ]
}

@test "crane not installed -> fails as a tooling error, not as missing manifests" {
  # The composite installs crane; if that step is skipped or fails, every lookup
  # errors at once. Reporting that as "nothing is published" is a wrong answer
  # that looks like a real one, so it must fail on the tool instead.
  rm -f "$CRANE_MOCK_DIR/crane"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"crane is not on PATH"* ]]
  [[ "$output" != *"does not exist"* ]]
}

@test "crane not installed under dry-run -> also fails, rather than warning falsely" {
  export INPUT_DRY_RUN="true"
  rm -f "$CRANE_MOCK_DIR/crane"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"crane is not on PATH"* ]]
  [[ "$output" != *"source manifests could not be resolved"* ]]
}

# Every string below is real crane v0.20.2 stderr, captured live against ghcr.io
# with the pinned version, so the classifier is pinned against what production
# actually prints rather than against invented registry JSON. crane renders the
# HTTP status itself and never surfaces MANIFEST_UNKNOWN/NAME_UNKNOWN, which is
# why an absent tag is recognised by "unexpected status code 404".
@test "classification: crane's absent-tag wording reads as absence" {
  export CRANE_MOCK_DIGEST_ERROR="2026/08/06 15:01:49 HEAD request failed, falling back on GET: HEAD https://ghcr.io/v2/example-org/example-image/manifests/9.9.9: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"does not exist"* ]]
  [[ "$output" != *"could not be inspected"* ]]
}

@test "classification: a refused token exchange reads as uninspectable" {
  # What an unreadable repo actually produces - the failure a soft rehearsal
  # login can cause. It must never be reported as absence.
  export CRANE_MOCK_DIGEST_ERROR="2026/08/06 15:01:50 No matching credentials were found for \"ghcr.io\", falling back on anonymous
2026/08/06 15:01:50 HEAD request failed, falling back on GET: GET https://ghcr.io/token?scope=repository%3Aexample-org%2Fexample-image%3Apull&service=ghcr.io: unexpected status code 403 Forbidden"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"could not be inspected"* ]]
  [[ "$output" != *"does not exist"* ]]
}

@test "classification: registry error codes still read as absence" {
  # crane does not emit these, but other registries and tools do; the arm is
  # kept deliberately, so pin it rather than leaving it unproven.
  for msg in "MANIFEST_UNKNOWN: manifest unknown" "NAME_UNKNOWN: repository name not known to registry"; do
    export CRANE_MOCK_DIGEST_ERROR="$msg"
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$output" == *"does not exist"* ]] || {
      echo "did not classify as absence: $msg"
      return 1
    }
  done
}

@test "classification: a bare 404 in transport noise does NOT read as absence" {
  # The pattern is "unexpected status code 404", not a bare "404": a host, digest
  # or proxy message carrying those digits must fall through to indeterminate.
  export CRANE_MOCK_DIGEST_ERROR="dial tcp: lookup registry-404.example.com: no such host"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"could not be inspected"* ]]
  [[ "$output" != *"does not exist"* ]]
}

@test "classification: mixed run -> each entry keeps its own verdict" {
  # The only case where the per-entry classification does work a single run-wide
  # verdict could not, so a regression hoisting it out of the loop fails here.
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9"
  set_digest_error "ghcr.io/example-org/example-image:9.9.9-fips" \
    "2026/08/06 15:01:50 GET https://ghcr.io/token?scope=x: unexpected status code 403 Forbidden"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"example-image:9.9.9 does not exist"* ]]
  [[ "$output" == *"example-image:9.9.9-fips could not be inspected"* ]]
  [[ "$output" == *"2 of 2 source manifests could not be resolved"* ]]
}

@test "rehearsal login failure -> named before the per-entry list, not left to inference" {
  export INPUT_DRY_RUN="true"
  export INPUT_LOGIN_OUTCOME="failure"
  export CRANE_MOCK_DIGEST_ERROR="2026/08/06 GET https://ghcr.io/token?scope=x: unexpected status code 403 Forbidden"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"the GHCR login did not succeed (failure)"* ]]
  # Assert the ordering the test is named for, not just presence: the whole point
  # is that the credential is stated BEFORE the per-entry list, so a regression
  # moving this warning into the entry loop must fail here.
  login_line=$(grep -n 'GHCR login did not succeed' <<<"$output" | head -1 | cut -d: -f1)
  first_entry=$(grep -n 'source manifest ghcr.io' <<<"$output" | head -1 | cut -d: -f1)
  [ -n "$login_line" ] && [ -n "$first_entry" ]
  [ "$login_line" -lt "$first_entry" ]
}

@test "login outcome is ignored on a real run and when unset" {
  # The rehearsal step is skipped on a real run, so its outcome is meaningless
  # there; an unwired or unresolved expression must not warn either.
  export INPUT_LOGIN_OUTCOME="skipped"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" != *"GHCR login did not succeed"* ]]

  export INPUT_DRY_RUN="true"
  export INPUT_LOGIN_OUTCOME=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" != *"GHCR login did not succeed"* ]]
}

@test "dry-run plan marks the lines whose source did not resolve" {
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  # Every moving tag of the unresolved entry is flagged, not only the first: the
  # marker is computed once per entry and printed per tag, so a regression that
  # cleared it after the first iteration would leave two of three lines reading
  # as healthy in a ~45-entry plan.
  [[ "$output" == *"Retagging ghcr.io/example-org/example-image:latest-fips -> ghcr.io/example-org/example-image:9.9.9-fips (WOULD FAIL: source unresolved)"* ]]
  [[ "$output" == *"Retagging ghcr.io/example-org/example-image:9-fips -> ghcr.io/example-org/example-image:9.9.9-fips (WOULD FAIL: source unresolved)"* ]]
  [[ "$output" == *"Retagging ghcr.io/example-org/example-image:9.9-fips -> ghcr.io/example-org/example-image:9.9.9-fips (WOULD FAIL: source unresolved)"* ]]
  # ...and the healthy sibling is not.
  [[ "$output" == *"Retagging ghcr.io/example-org/example-image:latest -> ghcr.io/example-org/example-image:9.9.9"* ]]
  [[ "$output" != *"example-image:latest -> ghcr.io/example-org/example-image:9.9.9 (WOULD FAIL"* ]]
}

@test "step summary names which refs were unresolved, not only how many" {
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9-fips"
  GITHUB_STEP_SUMMARY="$BATS_TEST_TMPDIR/summary.md"
  export GITHUB_STEP_SUMMARY
  : > "$GITHUB_STEP_SUMMARY"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF -- '- ghcr.io/example-org/example-image:9.9.9-fips: does not exist' "$GITHUB_STEP_SUMMARY"
}

@test "step summary caps the list at 20 and counts the rest" {
  # 25 entries, all unresolved: an off-by-one in the cap or the trailer would
  # otherwise pass, since no other test drives more than two.
  entries=$(jq -nc '[range(25) | {image: "ghcr.io/example-org/img\(.)"}]')
  export INPUT_IMAGES="$entries"
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_DIGEST_ERROR="2026/08/06 HEAD https://ghcr.io/v2/x/manifests/9.9.9: unexpected status code 404 Not Found"
  GITHUB_STEP_SUMMARY="$BATS_TEST_TMPDIR/summary.md"
  export GITHUB_STEP_SUMMARY
  : > "$GITHUB_STEP_SUMMARY"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [ "$(grep -c '^- ghcr.io/example-org/img' "$GITHUB_STEP_SUMMARY")" -eq 20 ]
  grep -qF -- '- (+5 more, see the warnings above)' "$GITHUB_STEP_SUMMARY"
  [[ "$output" == *"25 of 25 source manifests could not be resolved"* ]]
}

@test "aggregate hint follows the classes present, not a fixed string" {
  export INPUT_DRY_RUN="true"

  # Nothing absent: advising on the tag form would be the same misdirection the
  # per-entry split exists to prevent.
  export CRANE_MOCK_DIGEST_ERROR="2026/08/06 GET https://ghcr.io/token?scope=x: unexpected status code 403 Forbidden"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"check the credential and registry availability, not the tag form"* ]]
  [[ "$output" != *"rather than v9.9.9"* ]]

  # Something absent: the tag-form hint is the useful one.
  unset CRANE_MOCK_DIGEST_ERROR
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"their tags read 9.9.9 rather than v9.9.9"* ]]
  [[ "$output" != *"not the tag form"* ]]
}

@test "unresolved-sources is published as a step output" {
  # The only machine-readable signal that a rehearsed plan would not execute; a
  # caller keyed on the job conclusion cannot see it otherwise.
  GITHUB_OUTPUT="$BATS_TEST_TMPDIR/out.txt"
  export GITHUB_OUTPUT
  : > "$GITHUB_OUTPUT"
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_MISSING="ghcr.io/example-org/example-image:9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qx 'unresolved-sources=1' "$GITHUB_OUTPUT"

  : > "$GITHUB_OUTPUT"
  unset CRANE_MOCK_MISSING
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qx 'unresolved-sources=0' "$GITHUB_OUTPUT"
}

@test "digest lookup failure that isn't absence -> reported as uninspectable, not missing" {
  # A 401 on a private package, a rate limit or a DNS failure is not evidence
  # that the tag was never pushed; calling it missing would send an operator to
  # re-cut an image that is already published.
  export CRANE_MOCK_DIGEST_ERROR="UNAUTHORIZED: authentication required"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"could not be inspected"* ]]
  [[ "$output" == *"UNAUTHORIZED: authentication required"* ]]
  [[ "$output" != *"does not exist"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "dry-run digest failure that isn't absence -> warns as uninspectable, still rehearses" {
  export INPUT_DRY_RUN="true"
  export CRANE_MOCK_DIGEST_ERROR="TOOMANYREQUESTS: rate limit exceeded"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"could not be inspected"* ]]
  [[ "$output" == *"TOOMANYREQUESTS: rate limit exceeded"* ]]
  [[ "$output" != *"does not exist"* ]]
  [[ "$output" == *"2 of 2 source manifests could not be resolved"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "missing image field in an entry -> fails before any create call" {
  export INPUT_IMAGES='[{"image":"ghcr.io/example-org/example-image"},{"suffix":"-fips"}]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "malformed images JSON -> fails fast, no calls" {
  export INPUT_IMAGES='not json'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$CRANE_MOCK_CALLS" ]
}

@test "empty images array -> fails fast" {
  export INPUT_IMAGES='[]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
}

@test "missing GH_TOKEN -> fail fast, no calls" {
  unset GH_TOKEN
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$CRANE_MOCK_CALLS" ]
}

@test "missing GITHUB_REPOSITORY -> fail fast, no calls" {
  unset GITHUB_REPOSITORY
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$CRANE_MOCK_CALLS" ]
}

@test "missing version -> fail fast" {
  unset INPUT_VERSION
  run "$SCRIPT"
  [ "$status" -ne 0 ]
}

@test "crane retag failure -> aborts on the first create call" {
  export CRANE_MOCK_FAIL=1
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 1 ]
}

@test "gh release edit failure -> warns but does not fail the run (docker retags already done)" {
  export GH_MOCK_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"::warning::gh release edit failed for example-org/example-repo@v9.9.9"* ]]
  [[ "$output" == *"Docker retags are already complete. Promote manually"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "paired release edit failure -> skips Homebrew instead of advancing it ahead of the release" {
  export GH_MOCK_FAIL=1
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"gh release edit failed for example-org/example-repo@v9.9.9"* ]]
  [[ "$output" == *"skipping Homebrew tap promotion so the formula cannot advance ahead of the paired release"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> not configured by default, no download/api calls" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"No homebrew-tap-repo configured"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> patches version and per-artifact url/sha256, preserves everything else" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'DOWNLOAD example-org/example-repo v9.9.9 checksums.txt' "$GH_MOCK_CALLS"
  grep -qF 'API GET repos/example-org/example-tap/contents/Formula/vcluster.rb' "$GH_MOCK_CALLS"
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster.rb sha=fakesha' "$GH_MOCK_CALLS"

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  [ -f "$put_out" ]
  grep -qF 'version "9.9.9"' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-darwin-amd64' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-linux-amd64' "$put_out"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  grep -qF 'sha256 "dddd222222222222222222222222222222222222222222222222222222dddd"' "$put_out"
  run ! grep -qF 'v9.0.0' "$put_out"
  run ! grep -qF 'aaaa0000' "$put_out"
  run ! grep -qF 'bbbb0000' "$put_out"

  # Static content (deps, install blocks, test block) untouched.
  grep -qF 'desc "Example fake formula for tests"' "$put_out"
  grep -qF 'depends_on "helm"' "$put_out"
  grep -qF 'conflicts_with "vcluster-experimental"' "$put_out"
  grep -qF 'test do' "$put_out"
}

@test "homebrew tap -> backport skips entirely, no download/api calls" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_release_list "$INPUT_OSS_REPO" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"skipping Homebrew tap promotion entirely"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"

  # Skipping Homebrew is all-or-nothing: everything else still proceeds. The
  # caller repo's history is empty here (docker fully advances), and OSS_REPO
  # is the backport (prerelease unset, but no --latest).
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> caller backport skips even when the OSS Latest pointer is stale" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false,"isLatest":true}]'
  # OSS is behind and would independently classify v9.9.9 as an advance.
  set_release_list "$INPUT_OSS_REPO" '[{"tagName":"v9.0.0","isPrerelease":false,"isLatest":true}]'

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"behind the caller's promotion baseline"* ]]
  [[ "$output" == *"skipping Homebrew tap promotion entirely"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "homebrew-tap-repo without oss-repo -> fails fast" {
  export INPUT_OSS_REPO=""
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"homebrew-tap-repo requires oss-repo"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "homebrew-tap-repo without homebrew-formula-paths -> fails fast" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"homebrew-formula-paths must be a non-empty JSON array"* ]]
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 0 ]
}

@test "homebrew tap -> checksums download failure warns, skips homebrew, run still succeeds" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  export GH_MOCK_DOWNLOAD_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to download checksums.txt"* ]]
  run ! grep -q '^API ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> contents GET failure warns, skips that formula" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  export GH_MOCK_CONTENTS_GET_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to fetch example-org/example-tap/Formula/vcluster.rb"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> oss-repo list failure skips the tap as a retryable warning, not a false backport" {
  # Regression guard: a transient oss-repo list failure (soft) must NOT be
  # collapsed into the confirmed-backport state. The tap is skipped either way,
  # but the operator must see an accurate "could not confirm / retryable"
  # warning instead of a misleading "backport" notice that hides a stale
  # formula on what may be a genuine newest-release promotion.
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_LIST_FAIL_REPO="$INPUT_OSS_REPO"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"could not confirm v9.9.9 is the newest stable release on example-org/example-repo"* ]]
  [[ "$output" != *"(backport/patch promotion); skipping Homebrew"* ]]
  # No tap write, no checksums pulled - but everything upstream still ran.
  run ! grep -q '^API PUT\|^DOWNLOAD ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> oss-repo view failure stays retryable, not missing" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  export GH_MOCK_VIEW_FAIL_REPO="$INPUT_OSS_REPO"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to inspect example-org/example-repo@v9.9.9"* ]]
  [[ "$output" == *"could not inspect example-org/example-repo@v9.9.9 to source Homebrew checksums"* ]]
  [[ "$output" != *"no v9.9.9 release on example-org/example-repo to source checksums"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> undecodable formula content warns and skips, run still succeeds" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_CONTENTS_BAD_B64=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to decode example-org/example-tap/Formula/vcluster.rb contents"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> contents PUT failure warns but does not fail the run" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_API_PUT_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to update example-org/example-tap/Formula/vcluster.rb"* ]]
}

@test "homebrew tap -> dry-run reads contents/checksums but makes no real PUT" {
  export INPUT_DRY_RUN="true"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'API GET repos/example-org/example-tap/contents/Formula/vcluster.rb' "$GH_MOCK_CALLS"
  [[ "$output" == *"[dry-run] gh api -X PUT repos/example-org/example-tap/contents/Formula/vcluster.rb"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> multiple formula paths all get updated" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb","Formula/vcluster-experimental.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  cp "$FIXTURES_DIR/vcluster.rb" "$FIXTURES_DIR/vcluster-experimental.rb"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb" "$FIXTURES_DIR/vcluster-experimental.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster.rb sha=fakesha' "$GH_MOCK_CALLS"
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb sha=fakesha' "$GH_MOCK_CALLS"

  # Assert the second formula's committed body too, not just that a PUT fired -
  # a per-formula loop that diverged for formula #2 (wrong version, URL, or
  # sha256) would otherwise pass undetected.
  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb')"
  [ -f "$put_out" ]
  grep -qF 'version "9.9.9"' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-darwin-amd64' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-linux-amd64' "$put_out"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  grep -qF 'sha256 "dddd222222222222222222222222222222222222222222222222222222dddd"' "$put_out"
}

@test "homebrew tap -> missing checksum for an artifact warns, leaves its sha256 untouched" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  printf 'cccc111111111111111111111111111111111111111111111111111111cccc  vcluster-darwin-amd64\n' > "$FIXTURES_DIR/checksums-partial.txt"
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums-partial.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no checksum for vcluster-linux-amd64"* ]]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  # linux-amd64 had no replacement checksum, so its old sha256 survives.
  grep -qF 'sha256 "bbbb000000000000000000000000000000000000000000000000000000bbbb"' "$put_out"
  grep -qF 'version "9.9.9"' "$put_out"
}

@test "homebrew tap -> rewrites only the top-level version, leaves resource pins untouched" {
  write_fake_formula_with_resource "$FIXTURES_DIR/vcluster.rb"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  # Top-level version bumped; the resource stanza's own version pin preserved.
  grep -qF '  version "9.9.9"' "$put_out"
  grep -qF '    version "1.2.3"' "$put_out"
  [ "$(grep -c 'version "9.9.9"' "$put_out")" -eq 1 ]
  # The resource's unrelated url/sha256 (not a release-download URL) is untouched.
  grep -qF 'url "https://example.com/vendored-lib/1.2.3.tar.gz"' "$put_out"
  grep -qF 'sha256 "eeee000000000000000000000000000000000000000000000000000000eeee"' "$put_out"
}

@test "homebrew tap -> artifact names differing only at a regex metachar keep their own sha256" {
  write_fake_formula_metachar "$FIXTURES_DIR/vcluster.rb"
  write_fake_checksums_metachar "$FIXTURES_DIR/checksums.txt"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  # Each url's following sha256 must be its OWN artifact's checksum. A regex
  # matcher (the `.` in `vcluster-plugin.amd64` matching the `x` in
  # `vcluster-pluginxamd64`) would cross-assign these; a literal one can't.
  run grep -A1 -F 'download/v9.9.9/vcluster-plugin.amd64' "$put_out"
  [[ "$output" == *'sha256 "aaaa333333333333333333333333333333333333333333333333333333aaaa"'* ]]
  run grep -A1 -F 'download/v9.9.9/vcluster-pluginxamd64' "$put_out"
  [[ "$output" == *'sha256 "bbbb444444444444444444444444444444444444444444444444444444bbbb"'* ]]
}

@test "homebrew tap -> formula whose download tag isn't a release version is skipped, not mangled" {
  # The download tag is read from the (tap-committer-controlled) formula and
  # then used as literal data. A tag that isn't a recognizable release version
  # must warn-skip rather than flow into the patch - the guard that also keeps
  # such a value from ever reaching a shell/sed/regex or awk -v escape context.
  cat > "$FIXTURES_DIR/vcluster.rb" <<'RUBY'
class Vcluster < Formula
  version "9.0.0"
  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/not-a-version/vcluster-darwin-amd64"
    sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"
  end
end
RUBY
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"unrecognized version tag 'not-a-version'"* ]]
  # Advisory skip leaves the formula untouched (same as the "no download URL"
  # skip): the committed body is byte-for-byte the original - version and the
  # unrecognized download tag are both unchanged, nothing was mangled.
  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  grep -qF 'version "9.0.0"' "$put_out"
  grep -qF 'download/not-a-version/vcluster-darwin-amd64' "$put_out"
  run ! grep -qF 'download/v9.9.9/' "$put_out"
  [ "$(grep -c '^CREATE ' "$CRANE_MOCK_CALLS")" -eq 6 ]
}
