#!/usr/bin/env bats
# Tests for action.sh.
#
# Fixtures use an obviously-fake version (v9.9.9, not a real vcluster-pro
# release line) and fake images/repos (example-org/...), never real
# ghcr.io/loft-sh/* names or plausible real version numbers, so nobody
# mistakes test data for a real artifact.

bats_require_minimum_version 1.5.0

SCRIPT="$BATS_TEST_DIRNAME/../src/action.sh"

load gh_mock
load docker_mock

# Sets GH_MOCK_RELEASE_LIST_<repo> so is_latest_stable() sees a release
# history for that repo (see gh_mock.bash for the varname sanitization).
set_release_list() {
  local repo="$1" json="$2"
  local varname
  varname="GH_MOCK_RELEASE_LIST_$(printf '%s' "$repo" | tr -c 'A-Za-z0-9' '_')"
  export "$varname=$json"
}

# Points the `gh api GET repos/.../contents/<path>` mock at a real fixture
# file for the given full API path (e.g. "repos/example-org/example-tap/
# contents/Formula/vcluster.rb").
set_contents_fixture() {
  local api_path="$1" file="$2" sha="${3:-fakesha}"
  local suffix
  suffix="$(printf '%s' "$api_path" | tr -c 'A-Za-z0-9' '_')"
  export "GH_MOCK_CONTENTS_FILE_${suffix}=${file}"
  export "GH_MOCK_CONTENTS_SHA_${suffix}=${sha}"
}

# Points the `gh release download` mock at a real checksums.txt fixture for
# the given repo.
set_checksums_fixture() {
  local repo="$1" file="$2"
  local varname
  varname="GH_MOCK_CHECKSUMS_$(printf '%s' "$repo" | tr -c 'A-Za-z0-9' '_')"
  export "$varname=$file"
}

# Path the mock writes a PUT's decoded content to, for the given API path.
put_output_path() {
  printf '%s/put_%s.out' "$GH_MOCK_DIR" "$(printf '%s' "$1" | tr -c 'A-Za-z0-9' '_')"
}

write_fake_formula() {
  cat > "$1" <<'RUBY'
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  desc "Example fake formula for tests"
  homepage "https://example.com"
  version "9.0.0"
  license "Apache-2.0"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-darwin-amd64"
      sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"

      define_method(:install) do
        bin.install "vcluster-darwin-amd64" => "vcluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-linux-amd64"
      sha256 "bbbb000000000000000000000000000000000000000000000000000000bbbb"
      define_method(:install) do
        bin.install "vcluster-linux-amd64" => "vcluster"
      end
    end
  end

  conflicts_with "vcluster-experimental"

  test do
    help_output = "vcluster root command"
    assert_match help_output, shell_output("#{bin}/vcluster --help")
  end
end
RUBY
}

write_fake_checksums() {
  cat > "$1" <<'CHECKSUMS'
cccc111111111111111111111111111111111111111111111111111111cccc  vcluster-darwin-amd64
dddd222222222222222222222222222222222222222222222222222222dddd  vcluster-linux-amd64
CHECKSUMS
}

# A formula that carries a top-level `version` AND a nested resource stanza
# with its own `version` pin, to prove only the top-level one is rewritten.
write_fake_formula_with_resource() {
  cat > "$1" <<'RUBY'
# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  desc "Example fake formula for tests"
  version "9.0.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-darwin-amd64"
    sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"
  end

  resource "vendored-lib" do
    url "https://example.com/vendored-lib/1.2.3.tar.gz"
    version "1.2.3"
    sha256 "eeee000000000000000000000000000000000000000000000000000000eeee"
  end

  test do
    assert_match "vcluster", shell_output("#{bin}/vcluster --help")
  end
end
RUBY
}

# A formula whose two artifacts differ only where a regex `.` metacharacter
# would blur them (`vcluster-plugin.amd64` vs `vcluster-pluginxamd64`). A
# literal matcher keeps each url bound to its own sha256; a regex one would
# cross-contaminate them.
write_fake_formula_metachar() {
  cat > "$1" <<'RUBY'
# This file was generated by GoReleaser. DO NOT EDIT.
class Vcluster < Formula
  version "9.0.0"

  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-plugin.amd64"
    sha256 "1111000000000000000000000000000000000000000000000000000000aaaa"
  end

  on_linux do
    url "https://github.com/example-org/example-repo/releases/download/v9.0.0/vcluster-pluginxamd64"
    sha256 "2222000000000000000000000000000000000000000000000000000000bbbb"
  end
end
RUBY
}

write_fake_checksums_metachar() {
  cat > "$1" <<'CHECKSUMS'
aaaa333333333333333333333333333333333333333333333333333333aaaa  vcluster-plugin.amd64
bbbb444444444444444444444444444444444444444444444444444444bbbb  vcluster-pluginxamd64
CHECKSUMS
}

setup() {
  setup_gh_mock
  setup_docker_mock
  export GH_TOKEN="fake-token"
  export GITHUB_REPOSITORY="example-org/example-caller-repo"
  export INPUT_VERSION="v9.9.9"
  export INPUT_IMAGES='[{"image":"ghcr.io/example-org/example-image"},{"image":"ghcr.io/example-org/example-image","suffix":"-fips"}]'
  export INPUT_OSS_REPO="example-org/example-repo"
  export INPUT_DRY_RUN="false"
  export GH_MOCK_KNOWN_RELEASES="example-org/example-repo:v9.9.9"

  FIXTURES_DIR="$(mktemp -d)"
  write_fake_formula "$FIXTURES_DIR/vcluster.rb"
  write_fake_checksums "$FIXTURES_DIR/checksums.txt"
}

teardown() {
  teardown_gh_mock
  teardown_docker_mock
  rm -rf "$FIXTURES_DIR"
}

@test "happy path -> retags latest/major/minor for every image entry, including suffix" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9 ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:latest-fips ghcr.io/example-org/example-image:v9.9.9-fips' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9-fips ghcr.io/example-org/example-image:v9.9.9-fips' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-fips ghcr.io/example-org/example-image:v9.9.9-fips' "$DOCKER_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "happy path -> promotes the paired oss-repo release" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "newest stable over a non-empty prior-stable history -> advances :latest/:major" {
  # The happy path above drives is_latest_stable with an empty release list,
  # so it only exercises the `[ -z "${max}" ]` short-circuit. This is the real
  # forward-promotion case: a prior stable exists and VERSION is newer, so the
  # `sort -V | tail -1` comparison must resolve true and :latest still advances.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'CREATE ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9 ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "non-stable version (has a suffix) -> no-op, no docker or gh calls" {
  export INPUT_VERSION="v9.9.9-rc.1"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [ ! -s "$DOCKER_MOCK_CALLS" ]
  [ ! -s "$GH_MOCK_CALLS" ]
}

@test "every unstable suffix shape is a no-op -> never touches :latest or --latest" {
  # A human can uncheck "pre-release" on ANY release regardless of what its
  # tag looks like, so release:released can fire for an rc/alpha/beta/next
  # cut too - this is the guard that stops that from ever moving :latest.
  for version in \
    "v9.9.9-rc.1" \
    "v9.9.9-alpha.1" \
    "v9.9.9-beta.2" \
    "v9.9.9-next.3" \
    "v9.9.9-next.internal.7"
  do
    export INPUT_VERSION="$version"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" == *"is not a stable vX.Y.Z release"* ]]
    [ ! -s "$DOCKER_MOCK_CALLS" ]
    [ ! -s "$GH_MOCK_CALLS" ]
  done
}

@test "oss-repo has no matching release -> warns, still retags docker, does not edit" {
  export GH_MOCK_KNOWN_RELEASES=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no v9.9.9 release found on example-org/example-repo"* ]]
  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "empty oss-repo -> skips the paired release entirely" {
  export INPUT_OSS_REPO=""
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  # A "LIST" call for GITHUB_REPOSITORY's own backport check is expected;
  # what must NOT happen is any view/edit call touching an oss-repo.
  run ! grep -q '^VIEW \|^EDIT ' "$GH_MOCK_CALLS"
}

@test "dry-run -> prints planned retags, makes no real docker calls" {
  export INPUT_DRY_RUN="true"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"[dry-run] docker buildx imagetools create --tag ghcr.io/example-org/example-image:latest ghcr.io/example-org/example-image:v9.9.9"* ]]
  [ ! -s "$DOCKER_MOCK_CALLS" ]
}

@test "fail-closed dry-run -> any value that isn't exactly 'false' makes no real mutations" {
  # The safety inversion this guards: a caller who passes an ambiguous value
  # meaning to PREVIEW must never trigger a real GHCR retag / release flip.
  # Only an exact (case-insensitive) "false" promotes for real.
  for value in "true" "True" "TRUE" "yes" "1" "flase" "false " " false"; do
    : > "$DOCKER_MOCK_CALLS"
    : > "$GH_MOCK_CALLS"
    export INPUT_DRY_RUN="$value"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
    run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
  done
}

@test "fail-closed dry-run -> an unrecognized value warns and stays dry" {
  export INPUT_DRY_RUN="ture"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"unrecognized dry-run value 'ture'"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "fail-closed dry-run -> exact 'false' (and case variants) promotes for real" {
  # The default is 'false', so the release:released trigger still promotes; the
  # case-insensitive match means FALSE/False also cut for real rather than
  # silently degrading to a no-op.
  for value in "false" "False" "FALSE"; do
    : > "$DOCKER_MOCK_CALLS"
    export INPUT_DRY_RUN="$value"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
  done
}

@test "dry-run -> still reads oss-repo state but does not edit it" {
  export INPUT_DRY_RUN="true"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'VIEW example-org/example-repo v9.9.9' "$GH_MOCK_CALLS"
  run ! grep -q '^EDIT ' "$GH_MOCK_CALLS"
}

@test "backport on caller repo -> skips :latest/:major, still advances :major.minor" {
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v10.0.0","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not the newest stable release on example-org/example-caller-repo"* ]]

  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9-fips ghcr.io/example-org/example-image:v9.9.9-fips' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':latest ' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':9 ' "$DOCKER_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 2 ]

  # A different repo's history (oss-repo) is unaffected by the caller repo's:
  # the paired release still gets --latest.
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false --latest' "$GH_MOCK_CALLS"
}

@test "backport across minor lines (same major) -> still skips :latest/:major" {
  # Same shape as: promoting v0.35.6 after v0.36.0 already exists - a
  # same-major, older-minor patch. Distinct from the other backport test,
  # which only exercises a major-version jump (v9.9.9 vs v10.0.0); sort -V's
  # minor-component comparison is a separate thing to get right.
  export INPUT_VERSION="v9.35.6"
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.36.0","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not the newest stable release on example-org/example-caller-repo"* ]]

  grep -qF 'CREATE ghcr.io/example-org/example-image:9.35 ghcr.io/example-org/example-image:v9.35.6' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':latest ' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':9 ' "$DOCKER_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 2 ]
}

@test "same-minor out-of-order promotion -> skips :major.minor so the line tag can't regress" {
  # :9.9 already points at the newer v9.9.10 in the same line; a human then
  # un-checks pre-release on the older v9.9.9 (release:released fires for it).
  # It's not newest overall, so :latest/:9 are skipped - and because it's not
  # newest within its OWN 9.9 line either, :9.9 must be skipped too. Advancing
  # :9.9 here would silently regress it from v9.9.10 back to v9.9.9.
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.10","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"is not the newest stable release in the 9.9 line"* ]]
  [[ "$output" == *"no moving tags to advance"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "newest within its own line but not overall -> advances only :major.minor" {
  # v9.9.9 is the newest patch in the 9.9 line, but v10.0.0 exists overall.
  # This is the ordinary backport: :latest/:9 stay put, :9.9 still advances
  # (it isn't regressing - v9.9.9 IS the newest in its line).
  set_release_list "$GITHUB_REPOSITORY" '[{"tagName":"v9.9.8","isPrerelease":false},{"tagName":"v10.0.0","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'CREATE ghcr.io/example-org/example-image:9.9 ghcr.io/example-org/example-image:v9.9.9' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':latest ' "$DOCKER_MOCK_CALLS"
  run ! grep -qF ':9 ' "$DOCKER_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 2 ]
}

@test "backport on oss-repo -> paired release unsets prerelease but omits --latest" {
  set_release_list "$INPUT_OSS_REPO" '[{"tagName":"v10.0.0","isPrerelease":false}]'
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"not the newest stable release on example-org/example-repo"* ]]

  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"

  # The caller repo's own history is unaffected: docker tags fully advance.
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "oss-repo list failure (post-retag) -> soft-skips --latest, does not hard-fail the run" {
  # The caller-repo list runs pre-retag and still succeeds, so docker fully
  # retags. Only the oss-repo list fails - and it's post-retag, gating only the
  # advisory --latest. It must warn-skip --latest (never move it backward),
  # still unset prerelease, and keep the run green rather than hard-failing
  # after the irreversible retags already completed.
  export GH_MOCK_LIST_FAIL_REPO="$INPUT_OSS_REPO"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"skipping the advisory --latest promotion"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "caller-repo list failure (pre-retag) -> still fails closed with no retags" {
  # Contrast to the oss-repo case above: the caller-repo gate is pre-retag, so
  # an inability to determine ordering must hard-fail loudly (a green no-op
  # would hide a promotion that silently moved nothing).
  export GH_MOCK_LIST_FAIL_REPO="$GITHUB_REPOSITORY"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"failed to list releases on example-org/example-caller-repo"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "gh release list failure -> fails closed, does not treat it as no prior releases" {
  export GH_MOCK_LIST_FAIL=1
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"failed to list releases on example-org/example-caller-repo"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "missing source manifest for a suffix variant -> fails before any create call" {
  export DOCKER_MOCK_MISSING="ghcr.io/example-org/example-image:v9.9.9-fips"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"source manifest ghcr.io/example-org/example-image:v9.9.9-fips does not exist"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "missing image field in an entry -> fails before any create call" {
  export INPUT_IMAGES='[{"image":"ghcr.io/example-org/example-image"},{"suffix":"-fips"}]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "malformed images JSON -> fails fast, no calls" {
  export INPUT_IMAGES='not json'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$DOCKER_MOCK_CALLS" ]
}

@test "empty images array -> fails fast" {
  export INPUT_IMAGES='[]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
}

@test "missing GH_TOKEN -> fail fast, no calls" {
  unset GH_TOKEN
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$DOCKER_MOCK_CALLS" ]
}

@test "missing GITHUB_REPOSITORY -> fail fast, no calls" {
  unset GITHUB_REPOSITORY
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ ! -s "$DOCKER_MOCK_CALLS" ]
}

@test "missing version -> fail fast" {
  unset INPUT_VERSION
  run "$SCRIPT"
  [ "$status" -ne 0 ]
}

@test "docker push failure -> aborts on the first create call" {
  export DOCKER_MOCK_FAIL=1
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 1 ]
}

@test "gh release edit failure -> warns but does not fail the run (docker retags already done)" {
  export GH_MOCK_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"::warning::gh release edit failed for example-org/example-repo@v9.9.9"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> not configured by default, no download/api calls" {
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"No homebrew-tap-repo configured"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> patches version and per-artifact url/sha256, preserves everything else" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  grep -qF 'DOWNLOAD example-org/example-repo v9.9.9 checksums.txt' "$GH_MOCK_CALLS"
  grep -qF 'API GET repos/example-org/example-tap/contents/Formula/vcluster.rb' "$GH_MOCK_CALLS"
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster.rb sha=fakesha' "$GH_MOCK_CALLS"

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  [ -f "$put_out" ]
  grep -qF 'version "9.9.9"' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-darwin-amd64' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-linux-amd64' "$put_out"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  grep -qF 'sha256 "dddd222222222222222222222222222222222222222222222222222222dddd"' "$put_out"
  run ! grep -qF 'v9.0.0' "$put_out"
  run ! grep -qF 'aaaa0000' "$put_out"
  run ! grep -qF 'bbbb0000' "$put_out"

  # Static content (deps, install blocks, test block) untouched.
  grep -qF 'desc "Example fake formula for tests"' "$put_out"
  grep -qF 'depends_on "helm"' "$put_out"
  grep -qF 'conflicts_with "vcluster-experimental"' "$put_out"
  grep -qF 'test do' "$put_out"
}

@test "homebrew tap -> backport skips entirely, no download/api calls" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_release_list "$INPUT_OSS_REPO" '[{"tagName":"v10.0.0","isPrerelease":false}]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"skipping Homebrew tap promotion entirely"* ]]
  run ! grep -q '^DOWNLOAD \|^API ' "$GH_MOCK_CALLS"

  # Skipping Homebrew is all-or-nothing: everything else still proceeds. The
  # caller repo's history is empty here (docker fully advances), and OSS_REPO
  # is the backport (prerelease unset, but no --latest).
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "homebrew-tap-repo without oss-repo -> fails fast" {
  export INPUT_OSS_REPO=""
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"homebrew-tap-repo requires oss-repo"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "homebrew-tap-repo without homebrew-formula-paths -> fails fast" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  run "$SCRIPT"
  [ "$status" -ne 0 ]
  [[ "$output" == *"homebrew-formula-paths must be a non-empty JSON array"* ]]
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 0 ]
}

@test "homebrew tap -> checksums download failure warns, skips homebrew, run still succeeds" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  export GH_MOCK_DOWNLOAD_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to download checksums.txt"* ]]
  run ! grep -q '^API ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> contents GET failure warns, skips that formula" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  export GH_MOCK_CONTENTS_GET_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to fetch example-org/example-tap/Formula/vcluster.rb"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> oss-repo list failure skips the tap as a retryable warning, not a false backport" {
  # Regression guard: a transient oss-repo list failure (soft) must NOT be
  # collapsed into the confirmed-backport state. The tap is skipped either way,
  # but the operator must see an accurate "could not confirm / retryable"
  # warning instead of a misleading "backport" notice that hides a stale
  # formula on what may be a genuine newest-release promotion.
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_LIST_FAIL_REPO="$INPUT_OSS_REPO"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"could not confirm v9.9.9 is the newest stable release on example-org/example-repo"* ]]
  [[ "$output" != *"(backport/patch promotion); skipping Homebrew"* ]]
  # No tap write, no checksums pulled - but everything upstream still ran.
  run ! grep -q '^API PUT\|^DOWNLOAD ' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
  grep -qF -- 'EDIT example-org/example-repo v9.9.9 --prerelease=false' "$GH_MOCK_CALLS"
  run ! grep -qF -- '--latest' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> undecodable formula content warns and skips, run still succeeds" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_CONTENTS_BAD_B64=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to decode example-org/example-tap/Formula/vcluster.rb contents"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}

@test "homebrew tap -> contents PUT failure warns but does not fail the run" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  export GH_MOCK_API_PUT_FAIL=1
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"failed to update example-org/example-tap/Formula/vcluster.rb"* ]]
}

@test "homebrew tap -> dry-run reads contents/checksums but makes no real PUT" {
  export INPUT_DRY_RUN="true"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'API GET repos/example-org/example-tap/contents/Formula/vcluster.rb' "$GH_MOCK_CALLS"
  [[ "$output" == *"[dry-run] gh api -X PUT repos/example-org/example-tap/contents/Formula/vcluster.rb"* ]]
  run ! grep -q '^API PUT' "$GH_MOCK_CALLS"
}

@test "homebrew tap -> multiple formula paths all get updated" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb","Formula/vcluster-experimental.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"
  cp "$FIXTURES_DIR/vcluster.rb" "$FIXTURES_DIR/vcluster-experimental.rb"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb" "$FIXTURES_DIR/vcluster-experimental.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster.rb sha=fakesha' "$GH_MOCK_CALLS"
  grep -qF 'API PUT repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb sha=fakesha' "$GH_MOCK_CALLS"

  # Assert the second formula's committed body too, not just that a PUT fired -
  # a per-formula loop that diverged for formula #2 (wrong version, URL, or
  # sha256) would otherwise pass undetected.
  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster-experimental.rb')"
  [ -f "$put_out" ]
  grep -qF 'version "9.9.9"' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-darwin-amd64' "$put_out"
  grep -qF 'https://github.com/example-org/example-repo/releases/download/v9.9.9/vcluster-linux-amd64' "$put_out"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  grep -qF 'sha256 "dddd222222222222222222222222222222222222222222222222222222dddd"' "$put_out"
}

@test "homebrew tap -> missing checksum for an artifact warns, leaves its sha256 untouched" {
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  printf 'cccc111111111111111111111111111111111111111111111111111111cccc  vcluster-darwin-amd64\n' > "$FIXTURES_DIR/checksums-partial.txt"
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums-partial.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"no checksum for vcluster-linux-amd64"* ]]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  grep -qF 'sha256 "cccc111111111111111111111111111111111111111111111111111111cccc"' "$put_out"
  # linux-amd64 had no replacement checksum, so its old sha256 survives.
  grep -qF 'sha256 "bbbb000000000000000000000000000000000000000000000000000000bbbb"' "$put_out"
  grep -qF 'version "9.9.9"' "$put_out"
}

@test "homebrew tap -> rewrites only the top-level version, leaves resource pins untouched" {
  write_fake_formula_with_resource "$FIXTURES_DIR/vcluster.rb"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  # Top-level version bumped; the resource stanza's own version pin preserved.
  grep -qF '  version "9.9.9"' "$put_out"
  grep -qF '    version "1.2.3"' "$put_out"
  [ "$(grep -c 'version "9.9.9"' "$put_out")" -eq 1 ]
  # The resource's unrelated url/sha256 (not a release-download URL) is untouched.
  grep -qF 'url "https://example.com/vendored-lib/1.2.3.tar.gz"' "$put_out"
  grep -qF 'sha256 "eeee000000000000000000000000000000000000000000000000000000eeee"' "$put_out"
}

@test "homebrew tap -> artifact names differing only at a regex metachar keep their own sha256" {
  write_fake_formula_metachar "$FIXTURES_DIR/vcluster.rb"
  write_fake_checksums_metachar "$FIXTURES_DIR/checksums.txt"
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]

  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  # Each url's following sha256 must be its OWN artifact's checksum. A regex
  # matcher (the `.` in `vcluster-plugin.amd64` matching the `x` in
  # `vcluster-pluginxamd64`) would cross-assign these; a literal one can't.
  run grep -A1 -F 'download/v9.9.9/vcluster-plugin.amd64' "$put_out"
  [[ "$output" == *'sha256 "aaaa333333333333333333333333333333333333333333333333333333aaaa"'* ]]
  run grep -A1 -F 'download/v9.9.9/vcluster-pluginxamd64' "$put_out"
  [[ "$output" == *'sha256 "bbbb444444444444444444444444444444444444444444444444444444bbbb"'* ]]
}

@test "homebrew tap -> formula whose download tag isn't a release version is skipped, not mangled" {
  # The download tag is read from the (tap-committer-controlled) formula and
  # then used as literal data. A tag that isn't a recognizable release version
  # must warn-skip rather than flow into the patch - the guard that also keeps
  # such a value from ever reaching a shell/sed/regex or awk -v escape context.
  cat > "$FIXTURES_DIR/vcluster.rb" <<'RUBY'
class Vcluster < Formula
  version "9.0.0"
  on_macos do
    url "https://github.com/example-org/example-repo/releases/download/not-a-version/vcluster-darwin-amd64"
    sha256 "aaaa000000000000000000000000000000000000000000000000000000aaaa"
  end
end
RUBY
  export INPUT_HOMEBREW_TAP_REPO="example-org/example-tap"
  export INPUT_HOMEBREW_FORMULA_PATHS='["Formula/vcluster.rb"]'
  set_checksums_fixture "example-org/example-repo" "$FIXTURES_DIR/checksums.txt"
  set_contents_fixture "repos/example-org/example-tap/contents/Formula/vcluster.rb" "$FIXTURES_DIR/vcluster.rb"

  run "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"unrecognized version tag 'not-a-version'"* ]]
  # Advisory skip leaves the formula untouched (same as the "no download URL"
  # skip): the committed body is byte-for-byte the original - version and the
  # unrecognized download tag are both unchanged, nothing was mangled.
  put_out="$(put_output_path 'repos/example-org/example-tap/contents/Formula/vcluster.rb')"
  grep -qF 'version "9.0.0"' "$put_out"
  grep -qF 'download/not-a-version/vcluster-darwin-amd64' "$put_out"
  run ! grep -qF 'download/v9.9.9/' "$put_out"
  [ "$(grep -c '^CREATE ' "$DOCKER_MOCK_CALLS")" -eq 6 ]
}
