name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate-renovate:
    permissions:
      contents: read
      pull-requests: read
    uses: loft-sh/github-actions/.github/workflows/validate-renovate.yaml@e1593a4ab119917348fdc8cf743b3da9bea7dd58 # validate-renovate/v1

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: rhysd/actionlint@393031adb9afb225ee52ae2ccd7a5af5525e03e8  # v1.7.11

  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: pip install zizmor==1.23.1 && zizmor .github/
