name: Test cleanup-head-charts

on:
  pull_request:
    paths:
      - '.github/scripts/cleanup-head-charts/**'
      - '.github/workflows/cleanup-head-charts.yaml'

permissions: {}

jobs:
  bats:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
        with:
          tests: .github/scripts/cleanup-head-charts/test
