name: Test backport-legacy-split

on:
  pull_request:
    paths:
      - '.github/actions/backport-legacy-split/**'
      - '.github/workflows/test-backport-legacy-split.yaml'

permissions: {}

jobs:
  bats:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
        with:
          tests: .github/actions/backport-legacy-split/test
