name: Test publish-helm-chart

on:
  pull_request:
    paths:
      - '.github/scripts/publish-helm-chart/**'
      - '.github/workflows/publish-helm-chart.yaml'

permissions: {}

jobs:
  bats:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b # v1.3.1
        with:
          # renovate: datasource=github-releases depName=mikefarah/yq
          version: v4.45.1
      - uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
        with:
          tests: .github/scripts/publish-helm-chart/test
