name: Test run-ginkgo

on:
  pull_request:
    paths:
      - '.github/actions/run-ginkgo/**'
      - '.github/workflows/test-run-ginkgo.yaml'

permissions: {}

jobs:
  bats:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
        with:
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
      - name: Run run-ginkgo tests
        run: bats .github/actions/run-ginkgo/test/*.bats

  focus-selection:
    name: Run focus selection tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: .github/actions/run-ginkgo/test/focus/go.mod
      - run: go test -count=1 ./...
        working-directory: .github/actions/run-ginkgo/test/focus
